name: Release Creation

on:
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3


    - name: Load system manifest
      id: manifest
      uses: ActionsTools/read-json-action@main
      with:
        file_path: "./system.json"


    - name: Set up variables
      id: vars
      run: |
        VERSION=${GITHUB_REF/refs\/tags\//}
        SYSTEM_ID=${{steps.manifest.outputs.id}}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "SHORT_VERSION=${VERSION:8}" >> $GITHUB_ENV
        echo "SYSTEM_ID=$SYSTEM_ID" >> $GITHUB_ENV
        echo "ZIP_NAME=$SYSTEM_ID-$VERSION.zip" >> $GITHUB_ENV
        echo "RELEASE_DOWNLOAD_URL=https://github.com/${{github.repository}}/releases/download/$VERSION/$SYSTEM_ID-$VERSION.zip" >> $GITHUB_ENV
        echo "RELEASE_INSTALL_URL=https://github.com/${{github.repository}}/releases/download/$VERSION/system.json" >> $GITHUB_ENV


    - name: Adjust manifest
      uses: microsoft/variable-substitution@v1
      with:
        files: "system.json"
      env:
        download: ${{env.RELEASE_DOWNLOAD_URL}}
        version: ${{env.SHORT_VERSION}}
        flags.hotReload: false


    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'


    - name: Install Dependencies
      run: npm ci


    - name: Build All
      run: npm run build --if-present


    - name: Compile includes
      id: includes
      uses: actions/github-script@v6
      env:
        ESMODULES: ${{steps.manifest.outputs.esmodules}}
        FLAGS: ${{steps.manifest.outputs.flags}}
        LANGUAGES: ${{steps.manifest.outputs.languages}}
        PACKS: ${{steps.manifest.outputs.packs}}
        STYLES: ${{steps.manifest.outputs.styles}}
      with:
        result-encoding: string
        script: |
          const manifest = {
            esmodules: JSON.parse(process.env.ESMODULES),
            flags: JSON.parse(process.env.FLAGS),
            languages: JSON.parse(process.env.LANGUAGES),
            packs: JSON.parse(process.env.PACKS),
            styles: JSON.parse(process.env.STYLES)
          };
          const includes = [
            "system.json",
            "template.json",
            ...(manifest.esmodules ?? []),
            ...(manifest.esmodules?.map(s => `${s}.map`) ?? []),
            ...(manifest.styles ?? []),
            ...(manifest.packs?.map(p => p.path) ?? []),
            ...(manifest.languages?.map(l => l.path) ?? []),
            ...(manifest.flags?.build?.includes ?? [])
          ];
          return includes.join(" ");


    - name: Zip Contents
      run: zip ${{env.ZIP_NAME}} -r ${{steps.includes.outputs.result}}


    - name: Update Release with Files
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        name: ${{env.VERSION}}
        draft: false
        prerelease: ${{github.event.release.prerelease}}
        token: ${{secrets.GITHUB_TOKEN}}
        artifacts: './system.json, ./${{env.ZIP_NAME}}'
        tag: ${{env.VERSION}}
        body: |
          ${{github.event.release.body}}
          **Installation:** To manually install this release, please use the following manifest URL: ${{env.RELEASE_INSTALL_URL}}
